waist:
    uuid_matcher: '31F10002E85'
    joint_names: ['WAIST_R', 'WAIST_Y', 'WAIST_P']
    motor_ids: [13, 14, 15]
right_arm:
    uuid_matcher: '31F10002E89'
    joint_names: ['R_SHOULDER_P', 'R_SHOULDER_R', 'R_SHOULDER_Y', 'R_ELBOW_Y', 'R_WRIST_P', 'R_WRIST_Y', 'R_WRIST_R']
    motor_ids: [16, 17, 18, 19, 20, 21, 22]

left_arm:
    uuid_matcher: '31F100031D1'
    joint_names: ['L_SHOULDER_P', 'L_SHOULDER_R', 'L_SHOULDER_Y', 'L_ELBOW_Y', 'L_WRIST_P', 'L_WRIST_Y', 'L_WRIST_R']
    motor_ids: [23, 24, 25, 26, 27, 28, 29]

head:
    uuid_matcher: '31F10002E85'
    joint_names: ['NECK_Y', 'NECK_P', 'NECK_R']
    motor_ids: [30, 31, 32]
legs:
    uuid_matcher: '31F10002E85'
    joint_names: ['leg1', 'leg2', 'leg3']
    motor_ids: [100, 101, 102]